### ISSUE TITLE
Ubuntu 19.04 linking issues with GCC 7.4.0 and GCC 8.3.0. LLVM 8.0 works.

### ISSUE THREAD

**Issue by licensedslacker** [google/benchmark#835]
I have encountered a problem with linking while compiling benchmark sources with GCC versions delivered with Ubuntu 19.04 (Disco).

For instance, the sample application from README using libbenchmark 1.4.1 installed by APT:

> g++-8 -o benchmark -lpthread -lbenchmark -Wl,--trace sample.cpp

```
/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o
/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crti.o
/usr/lib/gcc/x86_64-linux-gnu/8/crtbeginS.o
/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libpthread.so
/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libbenchmark.so
/tmp/ccE5lFHC.o
/usr/lib/gcc/x86_64-linux-gnu/8/libstdc++.so
/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libm.so
/lib/x86_64-linux-gnu/libm.so.6
/usr/lib/x86_64-linux-gnu/libmvec_nonshared.a
/lib/x86_64-linux-gnu/libmvec.so.1
/usr/lib/gcc/x86_64-linux-gnu/8/libgcc_s.so
/usr/lib/gcc/x86_64-linux-gnu/8/libgcc_s.so.1
/usr/lib/gcc/x86_64-linux-gnu/8/libgcc.a
/usr/lib/gcc/x86_64-linux-gnu/8/libgcc.a
/usr/lib/gcc/x86_64-linux-gnu/8/libgcc.a
/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libc.so
/lib/x86_64-linux-gnu/libc.so.6
/usr/lib/x86_64-linux-gnu/libc_nonshared.a
/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
/usr/lib/x86_64-linux-gnu/libc_nonshared.a
/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
/usr/lib/gcc/x86_64-linux-gnu/8/libgcc_s.so
/usr/lib/gcc/x86_64-linux-gnu/8/libgcc_s.so.1
/usr/lib/gcc/x86_64-linux-gnu/8/libgcc.a
/usr/lib/gcc/x86_64-linux-gnu/8/libgcc.a
/usr/lib/gcc/x86_64-linux-gnu/8/crtendS.o
/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: /tmp/ccE5lFHC.o: in function `BM_StringCreation(benchmark::State&)':
sample.cpp:(.text+0x7a): undefined reference to `benchmark::State::StartKeepRunning()'
/usr/bin/ld: sample.cpp:(.text+0xbf): undefined reference to `benchmark::State::FinishKeepRunning()'
/usr/bin/ld: /tmp/ccE5lFHC.o: in function `BM_StringCopy(benchmark::State&)':
sample.cpp:(.text+0x205): undefined reference to `benchmark::State::StartKeepRunning()'
/usr/bin/ld: sample.cpp:(.text+0x24a): undefined reference to `benchmark::State::FinishKeepRunning()'
/usr/bin/ld: /tmp/ccE5lFHC.o: in function `main':
sample.cpp:(.text+0x32e): undefined reference to `benchmark::Initialize(int*, char**)'
/usr/bin/ld: sample.cpp:(.text+0x33f): undefined reference to `benchmark::ReportUnrecognizedArguments(int, char**)'
/usr/bin/ld: sample.cpp:(.text+0x34f): undefined reference to `benchmark::RunSpecifiedBenchmarks()'
/usr/bin/ld: /tmp/ccE5lFHC.o: in function `__static_initialization_and_destruction_0(int, int)':
sample.cpp:(.text+0x383): undefined reference to `benchmark::internal::InitializeStreams()'
/usr/bin/ld: sample.cpp:(.text+0x3b4): undefined reference to `benchmark::internal::RegisterBenchmarkInternal(benchmark::internal::Benchmark*)'
/usr/bin/ld: sample.cpp:(.text+0x3e6): undefined reference to `benchmark::internal::RegisterBenchmarkInternal(benchmark::internal::Benchmark*)'
/usr/bin/ld: /tmp/ccE5lFHC.o: in function `benchmark::internal::FunctionBenchmark::FunctionBenchmark(char const*, void (*)(benchmark::State&))':
sample.cpp:(.text._ZN9benchmark8internal17FunctionBenchmarkC2EPKcPFvRNS_5StateEE[_ZN9benchmark8internal17FunctionBenchmarkC5EPKcPFvRNS_5StateEE]+0x23): undefined reference to `benchmark::internal::Benchmark::Benchmark(char const*)'
/usr/bin/ld: sample.cpp:(.text._ZN9benchmark8internal17FunctionBenchmarkC2EPKcPFvRNS_5StateEE[_ZN9benchmark8internal17FunctionBenchmarkC5EPKcPFvRNS_5StateEE]+0x2a): undefined reference to `vtable for benchmark::internal::FunctionBenchmark'
collect2: error: ld returned 1 exit status
```
However, while checking library's symbols
> objdump -T -C /usr/lib/x86_64-linux-gnu/libbenchmark.so | grep benchmark::State::StartKeepRunning\(\)
```
0000000000017ac0 g    DF .text  0000000000000299  Base        benchmark::State::StartKeepRunning()
```

Errors are the same for GCC 7.4.0 and GCC 8.3.0. However, clang works fine with the same library! I assume this is related to gnu linker, but cannot figure out what would be the issue :(

Tried to build v1.5.0 from the sources, but got the same issues.

**Comment by LebedevRI** [comment]
I'd guess ABI mismatch.
Maybe you build with `-fno-rtti` while `benchmark` is built with `-frtti` or so?
Or different libc++?

**Comment by licensedslacker** [comment]
I think I managed to solve the issue. The GCC invocation was incorrect after all. I shall use `-pthread` instead of `-lpthread` and `-lbenchmark` shall be after the compilation unit.
The correct form should be:
> g++-8 -o benchmark -O2 -pthread sample.cpp -lbenchmark

This works with shared library version 1.4.1 provided APT and static library built by myself. I think clang is not that picky about the order of input files.

**Comment by raikrahul** [comment]
I have the same problem. 

None of the compilers can as suggested in the workaround can build the solution.

**Comment by dktapps** [comment]
> I shall use -pthread instead of -lpthread and -lbenchmark shall be after the compilation unit.

Saved my day. Still a problem with GCC 9.4. Thanks a ton @licensedslacker
