### ISSUE TITLE
benchmark::DoNotOptimize does not compile on gcc4.8 + ppc64

### ISSUE THREAD

**Issue by Maratyszcza** [google/benchmark#342]
I'm trying to build one of my projects on a ppc64le system, and compilation of benchmarks fails on assembly inside `benchmark::DoNotOptimize`:

```
/home/mdukhan3/NNPACK/deps/fxdiv/deps/googlebenchmark/include/benchmark/benchmark_api.h:236:45: error: cannot reload integer constant operand in ‘asm’
   asm volatile("" : : "g"(value) : "memory");
```

Results for `g++ -v`:
```
mdukhan3@power8:~/NNPACK/deps/fxdiv$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/powerpc64le-linux-gnu/4.8/lto-wrapper
Target: powerpc64le-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --disable-libsanitizer --disable-libsanitizer --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-ppc64el/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-ppc64el --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-ppc64el --with-arch-directory=ppc64el --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-secureplt --with-cpu=power7 --with-tune=power8 --enable-targets=powerpcle-linux --disable-multilib --enable-multiarch --disable-werror --with-long-double-128 --enable-checking=release --build=powerpc64le-linux-gnu --host=powerpc64le-linux-gnu --target=powerpc64le-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
```

**Comment by Maratyszcza** [comment]
Exactly the same problem on an ARMv7 system. `g++ -v`:

```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.8/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --enable-multilib --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.8.4 (Ubuntu/Linaro 4.8.4-2ubuntu1~14.04)
```

**Comment by EricWF** [comment]
[I can't reproduce on godbolt.org](https://godbolt.org/g/uPUHiY), including with GCC 4.8 on PowerPC.  You need to provide a full standalone reproducer including how you're using `DoNotOptimize` and all of the compile flags needed to reproduce or the target system.

**Comment by Maratyszcza** [comment]
[Here](https://gist.github.com/Maratyszcza/72e6d1f57092be2f8b09ca5fe506c634) is the preprocessed source: 

The error shows up when building `init-bench` target in [github.com/Maratyszcza/FXdiv](https://github.com/Maratyszcza/FXdiv).  Probably it is due to a POD structure being passed to `DoNotOptimize`: if I pass it by pointer instead, it compiles fine. However, there is another benchmark in this project (`divide-bench`) where I pass a POD structure to `DoNotOptimize`, and it compiles fine.

**Comment by EricWF** [comment]
@Maratyszcza Can you please provide a standalone reproducer? Preferably one that works on godbolt.

I'm afraid there's not much I can do if I can't reproduce.

**Comment by meastman** [comment]
Below is a standalone test case that fails for the following configurations on godbolt.org (all with `-Wall -Werror -std=c++0x -O3`):
- PowerPC 64 6.3.0
- PowerPC gcc 4.8
- ARM gcc 4.6.4
- x86-64 gcc 4.6.4
- x86-64 gcc 4.7.4

But works with the following:
- x86-64 gcc 4.8.1 (and above)
- x86-64 clang 3.4.1 (and above)
- MIPS64 gcc 5.4

```c++
#include <bitset>

template <class Tp>
inline void DoNotOptimize(Tp const& value) {
  asm volatile("" : : "g"(value) : "memory");
}

int main() {
    std::bitset<1> bitset;
    DoNotOptimize(bitset[0]);
}
```

**Comment by EricWF** [comment]
@meastman Awesome, Thank you for the reproducers! I've put together a patch that I believe should fix the issues.
