### ISSUE TITLE
[FR] Allow us to silence feature test output

### ISSUE THREAD

**Issue by DanielLiamAnderson** [google/benchmark#1466]
**Is your feature request related to a problem? Please describe.**
Whenever a feature test fails, it outputs the reason verbosely. For example, on Ubuntu 20.04 compiling with GCC 11, when `HAVE_GNU_POSIX_REGEX` is false, I get the following output:

```
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile: Change Dir: /home/runner/work/parlaylib/parlaylib/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_7afcd/fast && /usr/bin/make  -f CMakeFiles/cmTC_7afcd.dir/build.make CMakeFiles/cmTC_7afcd.dir/build
make[1]: Entering directory '/home/runner/work/parlaylib/parlaylib/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_7afcd.dir/gnu_posix_regex.cpp.o
/usr/bin/g++-7   -std=c++11  -Wall  -Wextra  -Wshadow  -Wfloat-equal  -Wsuggest-override  -pedantic  -pedantic-errors  -fstrict-aliasing  -Wno-deprecated-declarations  -Wstrict-aliasing  -o CMakeFiles/cmTC_7afcd.dir/gnu_posix_regex.cpp.o -c /home/runner/work/parlaylib/parlaylib/build/_deps/benchmark-src/cmake/gnu_posix_regex.cpp
/home/runner/work/parlaylib/parlaylib/build/_deps/benchmark-src/cmake/gnu_posix_regex.cpp:1:10: fatal error: gnuregex.h: No such file or directory
 #include <gnuregex.h>
          ^~~~~~~~~~~~
compilation terminated.
make[1]: *** [CMakeFiles/cmTC_7afcd.dir/build.make:78: CMakeFiles/cmTC_7afcd.dir/gnu_posix_regex.cpp.o] Error 1
make[1]: Leaving directory '/home/runner/work/parlaylib/parlaylib/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_7afcd/fast] Error 2
```

This change was introduced in #1426, here:

https://github.com/google/benchmark/blob/974cd5a5c5a78e76ebc50961f4dbf3bf6d4ade4e/cmake/CXXFeatureCheck.cmake#L67

This doesn't stop my build from configuring, but what it does do is scare my users who now **think** that the build didn't configure, because they see a bunch of verbose output that says scary words like "compilation terminated" and "error".

Users less familiar with CMake will undoubtedly mistake this for an actual error and wonder what is wrong, when nothing is actually wrong.

**Describe the solution you'd like**
Please introduce an option to silence this output. Even better if this option is enabled by default since end users really never need to see this.

**Describe alternatives you've considered**
I'm going to downgrade to an older version of Google Benchmark until this is better.

**Additional context**
N/A

**Comment by LebedevRI** [comment]
That seems like a debug leftover, it should be fine to remove it i would think.

**Comment by dominichamon** [comment]
yeah we can remove it again. i left it in because we've had issues in the past with these regex checks failing (usually due to some weird platform/flag mismatch between the build and try_compile) and this makes it easy to debug from the logs.

i'd like an option ideally that we can enable.

**Comment by dominichamon** [comment]
`--trace-expand` doesn't include the output by default. i think just adding a debug variable that can be toggled on would be enough.
